#!/usr/bin/env python3

import requests
import click

def fetch_observations(station):
    r = requests.get(f'https://api.weather.gov/stations/{station}/observations/latest')
    return r.json()['properties']

@click.group()
@click.pass_context
def cli(ctx):
    ...

@cli.command()
@click.option('-s', '--station', default='KBOS')
def bar(station):
    obs = fetch_observations(station)
    
    click.echo(f"{obs['temperature']['value']:.1f}c|{obs['barometricPressure']['value']/1e3:.0f}kPa")

if __name__ == '__main__':
    cli()
